export const color = {
  PRIMARY_COLOR: "#FFD400",
  SECONDARY_COLOR: "#302F4A",
  BACKGROUND_COLOR: "#25243A",
  TEXT_COLOR: "#FFFFFF",
  GRAY_TEXT_COLOR: "#AAAAAA",
  SECOND_TEXT_COLOR: "#0D2167",
  LINK_COLOR: "#FFFFFF",
  ERROR_COLOR: "",
  SUCCESS_COLOR: "",
  WARNING_COLOR: "",
  BORDER_COLOR: "",
};
